Change from fill_bytes to try_fill_bytes due to the trait bound error:
  error[E0599]: the method `fill_bytes` exists for struct `rand::rngs::OsRng`, but its trait bounds were not satisfied
    --> src/keys/rust_secp256k1.rs:27:19
     |
  27 |             OsRng.fill_bytes(&mut noncedata);
     |                   ^^^^^^^^^^
     |
    ::: /Users/akihito/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/os.rs:47:1
     |
  47 | pub struct OsRng;
     | ---------------- doesn't satisfy `rand::rngs::OsRng: rand::RngCore`, `rand::rngs::OsRng: std::ops::DerefMut` or `rand::rngs::OsRng: std::ops::Deref`
     |
     = note: the following trait bounds were not satisfied:
             `rand::rngs::OsRng: std::ops::DerefMut`
             which is required by `rand::rngs::OsRng: rand::RngCore`
             `rand::rngs::OsRng: std::ops::Deref`
             which is required by `rand::rngs::OsRng: rand::RngCore`